### ISSUE TITLE
move utility classes into a utility folder

### ISSUE THREAD

**Issue by ryanorsinger** [sakrog/listmorecoals#43]
Auth class and Input class belong in the utils folder because they are utility classes, not models.
Models are a special kind of class. Models represent a table in the database.

rule of thumb: 1-to-1 relationship between tables in the db and model classes.
Example:
User.php is the model for users table in the db
Ad.php is the model for ads in the db

**Comment by ryanorsinger** [comment]
Create a model for ads called Ad.php, this should extend BaseModel, and have the following:
public save() method
insert() method
update() method
delete() method
search() method

**Comment by ryanorsinger** [comment]
Add important getting started info to readme.md

Readme.md - Getting Started - how to join this project
    - what files you need that are .gitignore
    - what constants or variable names you need for the gitignored file

**Comment by pascalallen** [comment]
Moved Auth and Input into utils.
